Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Be.academy 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/05/2022
Var
    numero: inteiro
    i: inteiro


Inicio
       Para i de 2 ate 100 passo i+2 faca
       escreval("Os multiplos de 2 entre 0 e 100 são: " , i)
       fimpara

Fimalgoritmo