Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Be.academy 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/05/2022
Var
// Seção de Declarações das variáveis 
       nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
       escreva("Digite seu nome: ")
       leia(nome)
       escreva("Seja bem-vindo: " , nome)

Fimalgoritmo