Algoritmo "Tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Be.academy 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/05/2022
Var
    j, numero: inteiro

Inicio
    escreva("Digite o número para TABUADA: ")
    leia(numero)
    j<-1
    enquanto j < 11 faca
      escreval(numero, " x" ,j , " =",(numero*j))
     j <- j+1
    fimenquanto
    escreval ("Continuando após o enquanto")

Fimalgoritmo